enqueue:
  default:
    transport:
      dsn: '%env(KAFKA_URL)%'
      global:
        group.id: 'catalog-php'
        metadata.broker.list: "%env(KAFKA_BROKER_LIST)%"
      topic:
        auto.offset.reset: beginning
      commit_async: true
    client: ~
