version: "3"

networks:
    symfony:
        external: true

services:
    catalog-db-postgres:
        container_name: catalog-db-postgres
        hostname: catalog-db-postgres
        image: postgres
        restart: always
        env_file:
            - ./.env
        ports:
            - 5433:5432
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./docker/postgresql/data:/var/lib/postgresql/data
            - ./docker/postgresql/init:/docker-entrypoint-initdb.d

    catalog-php:
        container_name: catalog-php
        hostname: catalog-php
        env_file:
            - ./.env
        build:
            context: docker/php
            dockerfile: Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        ports:
            - 9001:9000
        volumes:
            - ./:/var/www/symfony/
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
            - ./docker/php/conf.d/php.ini-production:/usr/local/etc/php/php.ini-production
            - ./docker/php/conf.d/php.ini-development:/usr/local/etc/php/php.ini-development

    catalog-nginx:
        container_name: catalog-nginx
        hostname: catalog-nginx
        build:
            context: docker/nginx
        volumes:
            - ./:/var/www/symfony/
        ports:
            - 8081:80
        env_file:
            - docker/nginx/.env.nginx.local
