version: '2'

networks:
  symfony:
    external: true

services:
  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    image: docker.io/bitnami/elasticsearch:8
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  elasticsearch_data:
    driver: local
