version: "3"

services:
    db:
        image: mysql:8.0.23
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - type: bind
              source: ./docker/database/data
              target: /var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony
    php:
        container_name: symfony-php
        hostname: symfony-php
        build:
            context: docker/php
            dockerfile: Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        ports:
            - 9001:9000
        volumes:
            - ./:/var/www/symfony/
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        networks:
            - symfony
    nginx:
        build:
            context: docker/nginx
        volumes:
            - ./:/var/www/symfony/
        ports:
            - 8081:80
        networks:
            - symfony
        env_file:
            - docker/nginx/.env.nginx.local

networks:
  symfony:
    external: true

